language: cpp
sudo: false
addons:
        apt:
          packages:
          - libswiften-dev libprotobuf-dev protobuf-compiler pidgin-dev
script:
          - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make

